language: php

php:
  - 7.3
  - 7.4
  - nightly

sudo: enabled

# install hat-trie library in order to test HAT trie
before_script:
  - cd /usr/include
  - sudo git clone https://github.com/Tessil/hat-trie.git
  # - git clone -n https://github.com/Tessil/hat-trie.git --depth 1 && cd hat-trie && git checkout HEAD include/tsl/
  # - sudo mv hat-trie /usr/include/hat-trie

script:
  - phpize
  - ./configure --enable-php_trie
  - make && make test
