language: php

php:
  - 7.3
  - 7.4

os: linux

dist: bionic

# install hat-trie library in order to test HAT trie
before_script:
  - cd /usr/include
  - sudo git clone https://github.com/Tessil/hat-trie.git
  - cd $TRAVIS_BUILD_DIR

script:
  - phpize
  - ./configure --enable-php_trie
  - make && make test
