name: php-trie CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: ['7.3', '7.4', '8.0']
  name: PHP ${{ matrix.php }}
  steps:
    - uses: actions/checkout@v2
    - name: Install PHP
      uses: shivammathur/setup-php@master
      with:
        php-version: ${{ matrix.php }}
    - name: Install HAT trie
      run: git clone https://github.com/Tessil/hat-trie.git hat_trie
    - name: Build php-trie
      run: phpize && ./configure --enable-php-trie --with-hattrie=$(readlink -f `pwd`/hat_trie)
    - name: Install php-trie
      run: make && sudo make install
    - name: Configure php-trie
      run: echo "extension = php_trie.so" >> $(php -r 'echo php_ini_loaded_file();')
    - name: Run tests
      run: make test
